version: 2
updates:
- package-ecosystem: cargo
  directory: "/quotationservice"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/frontendservice"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
