pool:
  vmImage: ubuntu-18.04

variables:
  fortune_path: /dev/null
  fortune_service_hostname: fortuneservice
  getent_path: /usr/bin/getent

stages:
  - stage: Build
    jobs:
      # frontendservice
      - template: ci/azure-rustfmt.yml
        parameters:
          name: Rustfmt_frontendservice
          displayName: Rustfmt frontendservice
          folder: frontendservice

      - template: ci/azure-build-stable.yml
        parameters:
          name: Build_frontendservice
          displayName: Build frontendservice
          folder: frontendservice

      # fortuneservice
      - template: ci/azure-rustfmt.yml
        parameters:
          name: Rustfmt_fortuneservice
          displayName: Rustfmt fortuneservice
          folder: fortuneservice

      - template: ci/azure-build-stable.yml
        parameters:
          name: Build_fortuneservice
          displayName: Build fortuneservice
          folder: fortuneservice
