variables:
  fortune_path: /dev/null
  fortune_service_hostname: fortuneservice
  getent_path: /usr/bin/getent

jobs:
  # frontendservice
  - template: ci/azure-rustfmt.yml
    parameters:
      name: Rustfmt_frontendservice
      displayName: Rustfmt frontendservice
      vmImage: ubuntu-16.04
      folder: frontendservice

  - template: ci/azure-build-stable.yml
    parameters:
      name: Build_frontendservice
      displayName: Build frontendservice
      vmImage: ubuntu-16.04
      folder: frontendservice

  # fortuneservice
  - template: ci/azure-rustfmt.yml
    parameters:
      name: Rustfmt_fortuneservice
      displayName: Rustfmt fortuneservice
      vmImage: ubuntu-16.04
      folder: fortuneservice

  - template: ci/azure-build-stable.yml
    parameters:
      name: Build_fortuneservice
      displayName: Build fortuneservice
      vmImage: ubuntu-16.04
      folder: fortuneservice
