trigger: ["master"]
pr: ["master"]

variables:
  fortune_path: /dev/null

jobs:
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt

# Basic test run on all platforms
- template: ci/azure-build-stable.yml
  parameters:
    name: Linux_Stable
    displayName: Build
    vmImage: ubuntu-16.04
    crates:
      - fortuneservice
      - frontendservice
