trigger: ["master"]
pr: ["master"]

variables:
  fortune_path: /dev/null
  fortune_service_hostname: fortuneservice
  getent_path: /usr/bin/getent

jobs:
- template: ci/azure-rustfmt.yml
  parameters:
    name: Rustfmt
    displayName: Rustfmt
    vmImage: ubuntu-16.04
    crates:
      - fortuneservice
      - frontendservice

# Basic test run on all platforms
- template: ci/azure-build-stable.yml
  parameters:
    name: Build
    displayName: Build
    vmImage: ubuntu-16.04
    crates:
      - fortuneservice
      - frontendservice
