trigger: ["master"]
pr: ["master"]

parameters:
  services:
    - frontendservice
    - fortuneservice

variables:
  fortune_path: /dev/null
  fortune_service_hostname: fortuneservice
  getent_path: /usr/bin/getent

jobs:
  - ${{ each service in parameters.services }}:
    - template: ci/azure-rustfmt.yml
      parameters:
        name: ${{ service }}
        displayName: Rustfmt ${{ service }}
        vmImage: ubuntu-16.04

    - template: ci/azure-build-stable.yml
      parameters:
        name: ${{ service }]
        displayName: Build ${{ service }}
        vmImage: ubuntu-16.04
