apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: databaseservice
    context: databaseservice
  - image: quotationservice
    context: quotationservice
  - image: frontendservice
    context: frontendservice
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
