apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: fortuneservice
    context: fortuneservice
  - image: frontendservice
    context: frontendservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# "github-ci" profile is used to build the images without
# pushing them.
- name: github-ci
  build:
    local:
      push: false
