[package]
name = "frontend-server"
version = "0.1.0"
authors = ["Pradip Caulagi <caulagi@gmail.com>"]
edition = "2018"

[[bin]]
name = "frontend-server"
path = "src/main.rs"

[dependencies]
bytes = "1.0"
log = "0.4"
pretty_env_logger = "0.4.0"
prost = "0.6"
tokio = { version = "1.0.1", features = ["rt-multi-thread", "net", "macros"] }
tonic = { version = "0.3.1", features = ["tls"] }
# TODO: disable default-features
warp = { version = "0.2.5" }
tokio-compat-02 = "0.1.2"

[build-dependencies]
tonic-build = { version = "0.3.1" }
