[package]
name = "quotation-server"
version = "0.1.0"
authors = ["Pradip Caulagi <caulagi@gmail.com>"]
edition = "2018"

license = "MIT"

[[bin]]
name = "quotation-server"
path = "src/main.rs"

[dependencies]
bytes = "0.6"
log = "0.4"
pretty_env_logger = "0.4.0"
prost = "0.6"
tokio = { version = "0.2.22", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
tokio-postgres = { version = "0.5.5" }
tonic = { version = "0.3.1", features = ["tls"] }

[build-dependencies]
tonic-build = { version = "0.3.1" }
