# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysecret
# type: Opaque
# data:
#   username: YWRtaW4=
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-postgres-data
#   labels:
#     etiqueta: pv-postgres-etc
# spec:
#   capacity:
#     storage: 200Mi
#   accessModes:
#     - ReadOnlyMany
#   persistentVolumeReclaimPolicy: Recycle
#   hostPath:
#     path: data/data.sql
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 4Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: pvc-postgres-data
# spec:
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 50Mi
#   selector:
#     matchLabels:
#       etiqueta: pv-postgres-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      # volumes:
      #   - name: postgres-data
      #     persistentVolumeClaim:
      #       claimName: pvc-postgres-data
      # volumes:
      #   - name: postgres-initial-data
      #     hostPath:
      #       path: data/data.sql
      #       type: File
      containers:
        - name: databaseservice
          image: databaseservice
          ports:
            - containerPort: 5432
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: 5432
          # volumeMounts:
          #   - name: postgres-initial-data
          #     mountPath: /docker-entrypoint-initdb.d/01-data.sql
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: pgpassword
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
