apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortuneservice
spec:
  selector:
    matchLabels:
      app: fortuneservice
  template:
    metadata:
      labels:
        app: fortuneservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: fortuneservice
          image: fortuneservice
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          env:
            - name: RUST_LOG
              value: fortune=debug
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: pgpassword
            - name: POSTGRES_SERVICE
              value: postgres-service
          # readinessProbe:
          #   initialDelaySeconds: 20
          #   periodSeconds: 15
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
          # livenessProbe:
          #   initialDelaySeconds: 20
          #   periodSeconds: 15
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: fortuneservice
spec:
  type: ClusterIP
  selector:
    app: fortuneservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
