apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotationservice
spec:
  selector:
    matchLabels:
      app: quotationservice
  template:
    metadata:
      labels:
        app: quotationservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: quotationservice
          image: quotationservice
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          env:
            - name: RUST_LOG
              value: quotation=debug
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: pgpassword
            - name: POSTGRES_SERVICE
              value: postgres-service
          # readinessProbe:
          #   initialDelaySeconds: 20
          #   periodSeconds: 15
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
          # livenessProbe:
          #   initialDelaySeconds: 20
          #   periodSeconds: 15
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: quotationservice
spec:
  type: ClusterIP
  selector:
    app: quotationservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
