jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable
  - bash: |
        rustup component add rustfmt
  - script: cargo fmt -- --check
    displayName: cargo fmt
    workingDirectory: $(Build.SourcesDirectory)/${{ parameters.folder }}
