parameters:
  crates: []

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable
  - script: cargo build
    displayName: cargo build
    workingDirectory: $(Build.SourcesDirectory)/${{ parameters.folder }}
