name: Build & test project

on:
  - push

jobs:
  build-frontend:
    name: Check frontendservice
    if: "!startsWith(github.event.head_commit.message, '[ci skip]') || !startsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build frontendservice
        working-directory: frontendservice
        run: cargo build
        env:
          GETENT_PATH: /usr/bin/getent
          RUST_LOG: frontend=info
      - name: Check format frontendservice
        working-directory: frontendservice
        run: cargo fmt -- --check

  build-fortune:
    name: Check fortuneservice
    if: "!startsWith(github.event.head_commit.message, '[ci skip]') || !startsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build fortuneservice
        working-directory: fortuneservice
        run: cargo build
        env:
          FORTUNE_PATH: /usr/bin/fortune
          RUST_LOG: fortune=info
      - name: Check format fortuneservice
        working-directory: fortuneservice
        run: cargo fmt -- --check

  integration-test:
    name: Integration test
    if: github.ref == 'disabled'
    needs:
      - build-frontend
      - build-fortune
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install latest version of Kind
        run: GO111MODULE=on go get sigs.k8s.io/kind
      - name: Create Kind cluster
        run: |
          PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml
          # https://github.com/GoogleContainerTools/skaffold/issues/3296
          kubectl config rename-context "kind-kind" "kind-kind@kind"
      - name: Install metallb
        run: kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
      - name: Start application
        run: ./skaffold run --profile github-ci
      - name: Wait for kubectl rollout status
        run: |
          kubectl rollout status -w deployments/fortuneservice
          kubectl rollout status -w deployments/frontendservice
      - name: Run integration test
        run: |
          SERVICE_IP=$(kubectl get svc --selector=app=frontend,component=loadbalancer -o json | jq --raw-output ".items[0].status.loadBalancer.ingress[0].ip")
          test 200 = $(curl -sL -w "%{http_code}\\n" http://$SERVICE_IP -o /dev/null)
