name: "Close stale issues"
on:
  schedule:
  - cron: "0 4 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen recent activity. It will be closed soon, unless there is an update'
        stale-pr-message: 'This PR has not seen recent activity. It will be closed soon, unless there is an update'
        days-before-stale: 300
        days-before-close: 30
        exempt-pr-label: no-stale
        exempt-issue-label: no-stale
        stale-issue-label: stale
        stale-pr-label: stale
